### ISSUE TITLE
Bearer Authorization header

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#5]
Show the button of Authorization 

Bearer  (apiKey)
Name: Authorization
In: header

![image](https://user-images.githubusercontent.com/13761652/69718658-98945780-1117-11ea-9304-661510a6f6ea.png)

**Comment by aabuhasan** [comment]
`"securityDefinitions": {
        "Bearer": {
            "name": "Authorization",
            "in": "header",
            "type": "apiKey",
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
        }
    },
    "security": [
        {
            "Bearer": []
        }`

**Comment by athiththan11** [comment]
Hi @aabuhasan 

Please find the commit for the above-reported issue [#5f825ed](https://github.com/athiththan11/FHIR-to-Swagger/commit/5f825edce4d0813ba223649b3f3a688f072d1f9e)
Hope this solves your requirement.

Cheers !!!
