### ISSUE TITLE
Enum as dropdown list

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#6]
Show dropdown list for enums 

![image](https://user-images.githubusercontent.com/13761652/69718871-017bcf80-1118-11ea-98c0-f6fdacaa0a0d.png)

**Comment by athiththan11** [comment]
Hi @aabuhasan 

I don't have much depth (and experience) about the FHIR resources and supported enums for the parameters defined. Therefore, it would be much easier if you can point me out and navigate me to some of the supported enums for the Status query parameter (and other related schemas).

Glad to have it as an enhancement.
Cheers !!!

**Comment by athiththan11** [comment]
**Enhancement Fix #13** 
Now FHIR-to-Swagger supports enums in the generated Swagger definitions
