### ISSUE TITLE
List of produces 

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#7]
` "produces": [
                    "text/plain",
                    "application/json",
                    "application/fhir+json",
                    "application/json+fhir",
                    "text/json",
                    "application/xml",
                    "application/fhir+xml",
                    "application/xml+fhir",
                    "text/xml",
                    "text/xml+fhir",
                    "application/octet-stream"
                ],`

**Comment by athiththan11** [comment]
HI @aabuhasan 

Please find the commit for the above-reported issue [#2f627f2](https://github.com/athiththan11/FHIR-to-Swagger/commit/2f627f2e85be0f36f5eb8bf26608d5e7df31e1d0)
Hope this solves your requirement.

Cheers !!!
