### ISSUE TITLE
Summary and description 

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#8]
` "/fhir/Claim/{id}/_history/{vid}": {
            "get": {
                "tags": [
                    "Claim"
                ],
                "summary": "Get claim history",
                "description": "Get claim history by providing transaction id and version"`

**Comment by athiththan11** [comment]
Hi @aabuhasan 

Please find the commit for the above-reported issue [#a600fc0](https://github.com/athiththan11/FHIR-to-Swagger/commit/a600fc0ad3f9f503198be5af841f220a38835a0a)
Hope this solves your requirement.

Cheers !!!
