### ISSUE TITLE
Add the option to include delete and put.

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#9]
fhir-to-swagger Claim ClaimResponse  --generate "Delete Get Put" or 

fhir-to-swagger Claim ClaimResponse  --generate "Post Get Put"

**Comment by athiththan11** [comment]
Enhancement made on PR #12

**Comment by athiththan11** [comment]
## Enhancement

FHIR-to-Swagger now supports to include Verb actions while generating the Swagger definitions for the FHIR Resources

```sh
fhir-to-swagger Coverage --verbs put delete --output .
```

```sh
fhir-to-swagger Coverage Claim --combine --verbs coverage.get claim.put delete --output .
````
